apiVersion: v1
kind: Pod
metadata:
  name: node-name-test
  namespace: abc
spec:
  restartPolicy: Never
  containers:
  - image: tutum/dnsutils:latest
    command: ["nslookup", "$(NODE_NAME)"]
    name: node-name
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
